#print("Hello")
#a=10
#print(a)
mytuple=(10,20,30,40,50)
print(mytuple)
print(mytuple[2])
print(len(mytuple))
print(mytuple)
mytuple1=("air","water","wind","soil")
print(mytuple+mytuple1)
mytuple2=mytuple1
print(f"id of mytuple1  {id(mytuple1)} ")
print(f"mytuple2)+id(mytuple2)")
print(mytuple[::-1])
print(mytuple[-1])
print(mytuple[1:3])

#print(mytuple[1,3])
print("********************************************************************************")
mytuple1=("apple", "orange", "cherry")
print(mytuple1[0])
print(mytuple1[-1])
print(mytuple1[1:3])
print(mytuple1[::-1])
