from time import sleep

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By

s=Service("C://chromedriver.exe")
driver = webdriver.Chrome(service=s)
#driver.get("https://www.globalsqa.com/samplepagetest/")
#print(driver.find_element(By.NAME,"g2599-expertise[]").is_selected())
#driver.find_element(By.NAME,"g2599-expertise[]").click()
#print(driver.find_element(By.NAME,"g2599-expertise[]").is_selected())
#driver.get("https://www.makemytrip.com/")
#driver.maximize_window()
#sleep(10)
#print(driver.find_element(By.XPATH,"//li[@data-cy='roundTrip']").is_selected())
#driver.find_element(By.XPATH,"//li[@data-cy='roundTrip']").click()
#sleep(10)
#print(driver.find_element(By.XPATH,"//li[@data-cy='roundTrip']").is_selected())
#driver.get("https://login.salesforce.com/")
#driver.maximize_window()
#print(driver.current_url)
#print(driver.title)
#print(driver.find_element(By.ID,"rememberUn").is_selected())
#driver.find_element(By.ID,"rememberUn").click()
#print(driver.find_element(By.ID,"rememberUn").is_selected())
#print(driver.find_element(By.ID,"Login").is_enabled())
#print((driver.find_element(By.XPATH,"//p[@class='di mr16']")).is_enabled())
#sleep(20)
#print(driver.find_element(By.ID,"direct-flight-toggle-96787846bfeff").is_displayed())
#print(driver.find_element(By.ID,"direct-flight-toggle-96787846bfeff").is_selected())
#driver.find_element(By.ID,"direct-flight-toggle-96787846bfeff").click()
#print(driver.find_element(By.ID,"direct-flight-toggle-96787846bfeff").is_selected())
#driver.find_element(By.XPATH,"//a[@id='u_0_0_e1']").click()
#print(driver.find_element(By.XPATH,"//input[@id='u_b_4_Jp']").is_selected())
#driver.find_element(By.XPATH,"//input[@id='u_b_4_Jp']").click()
#print(driver.find_element(By.XPATH,"//input[@id='u_b_4_Jp']").is_selected())
driver.get("https://www.makemytrip.com/")
driver.maximize_window()
sleep(10)
driver.find_element(By.XPATH,'//div[@data-cy="LanguageSwitcherWidget"]').click()
print(driver.find_element(By.ID,"engLang").is_selected())

#driver.find_element(By.XPATH,"//p[text()='Login or Create Account']").click()
#print(driver.find_element(By.XPATH,"//button[@data-cy='continueBtn']").is_enabled())
#driver.find_element(By.XPATH,"//input[@id='username']").send_keys("Test@gmail.com")
#print(driver.find_element(By.XPATH,"//button[@data-cy='continueBtn']").is_enabled())
#driver.find_element(By.XPATH,"//button[@data-cy='continueBtn']").click()
#sleep(10)